name: RealClock
version: 1.1.0
description: Provides commands for checking local time based on IP.
author: taytom258

main: net.ddns.taytom258.SpigotRealClockPlugin.Plugin
database: false
load: STARTUP
softdepend: [PermissionsEx, ProtocolLib]

commands:
  realclock:
    description: Provides access to RealClock commands
    aliases: [RealClock, Realclock, realClock, rc]
    usage: |
           ยง6Usage:
           /<command> - Display local time based on IP
           /<command> ip - Display local IP used in time calculations
           /<command> reload - Reload RealClock config file
           /<command> mm - Toggle Maintenance Mode

permissions:
  realclock.clock:
    default: true
    description: Give players with op, clock command
  realclock.clock.ip:
    default: true
    description: Give players with op, ip command
  realclock.reload:
    default: op
    description: Give players with op, reload ability
  realclock.mm.bypass:
    default: op
    description: Give players with op, the ability to bypass mm
  realclock.mm.toggle:
    default: op
    description: Give players with op, the ability to toggle mm
  realclock.bypass:
    default: false
    description: This permission is only for testing