name: RealClock
version: 1.0.1-SNAPSHOT
description: Provides commands for checking local time based on IP.
author: taytom258

main: net.ddns.taytom258.SpigotRealClockPlugin.Plugin
database: false
load: STARTUP

commands:
  clock:
    description: Provides access to RealClock commands
    usage: |
           ยง6Usage:
           /<command> - Display local time based on IP
           /<command> ip - Display local IP used in time calculations
    
permissions:
  realclock.clock:
    default: op
    description: Give players with op clock command
  realclock.clock.ip:
    default: op
    description: Give players with op ip command
  realclock.bypass:
    default: false
    description: This permission is only for testing